# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsertCourseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InsertCourseWindow(object):
    def setupUi(self, InsertCourseWindow):
        InsertCourseWindow.setObjectName("InsertCourseWindow")
        InsertCourseWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(InsertCourseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(230, 130, 251, 310))
        self.frame.setMinimumSize(QtCore.QSize(251, 310))
        self.frame.setMaximumSize(QtCore.QSize(251, 310))
        self.frame.setStyleSheet("#frame\n"
"{\n"
"    border:1px solid;\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"    background-color: rgb(233, 255, 255);\n"
"    border-radius:20px;\n"
"    font: 9pt \"Adobe 黑体 Std R\";\n"
"\n"
"}\n"
"QLineEdit\n"
"{\n"
"    border:none;\n"
"    border-bottom:1px solid;\n"
"    background-color: rgb(233, 255, 255);\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16))
        self.pushButton.setStyleSheet("border:none;\n"
"background-color: rgb(233, 255, 255);\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setStyleSheet("    font: 11pt \"Adobe 黑体 Std R\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_id = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout.addWidget(self.lineEdit_id)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_6.addWidget(self.lineEdit_name)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_sex = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sex.setObjectName("lineEdit_sex")
        self.horizontalLayout_7.addWidget(self.lineEdit_sex)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_age = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.horizontalLayout_8.addWidget(self.lineEdit_age)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEdit_year = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.horizontalLayout_9.addWidget(self.lineEdit_year)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_class = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_class.setObjectName("lineEdit_class")
        self.horizontalLayout_10.addWidget(self.lineEdit_class)
        self.verticalLayout.addWidget(self.frame_7)
        self.pushButton_sure = QtWidgets.QPushButton(self.frame)
        self.pushButton_sure.setMinimumSize(QtCore.QSize(50, 20))
        self.pushButton_sure.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_sure.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(216, 216, 216);\n"
"}\n"
"")
        self.pushButton_sure.setObjectName("pushButton_sure")
        self.verticalLayout.addWidget(self.pushButton_sure, 0, QtCore.Qt.AlignHCenter)
        InsertCourseWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InsertCourseWindow)
        self.pushButton.clicked.connect(InsertCourseWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InsertCourseWindow)

    def retranslateUi(self, InsertCourseWindow):
        _translate = QtCore.QCoreApplication.translate
        InsertCourseWindow.setWindowTitle(_translate("InsertCourseWindow", "InsertCourseWindow"))
        self.label_11.setText(_translate("InsertCourseWindow", "Insert info for course"))
        self.label.setText(_translate("InsertCourseWindow", "course\'ID:"))
        self.label_6.setText(_translate("InsertCourseWindow", "name: "))
        self.label_7.setText(_translate("InsertCourseWindow", "teacher\'ID:"))
        self.label_8.setText(_translate("InsertCourseWindow", "credit:"))
        self.label_9.setText(_translate("InsertCourseWindow", "grade:"))
        self.label_10.setText(_translate("InsertCourseWindow", "canceled year:"))
        self.pushButton_sure.setText(_translate("InsertCourseWindow", "确认"))
import res_rc
