# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 793)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/homeicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 40, 861, 591))
        self.frame_2.setMinimumSize(QtCore.QSize(861, 591))
        self.frame_2.setStyleSheet("#frame_2\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("border:none;\n"
"font: 12pt \"幼圆\";")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_3.addWidget(self.pushButton_logout)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minimizing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6\n"
"{\n"
"    border-bottom-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    background-color: rgba(69, 119, 255,150);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 13pt \"幼圆\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(202, 202, 202);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:4px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.pushButton_stu_info = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_stu_info.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_stu_info.setObjectName("pushButton_stu_info")
        self.verticalLayout_2.addWidget(self.pushButton_stu_info)
        self.pushButton_tea_info = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_tea_info.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_tea_info.setObjectName("pushButton_tea_info")
        self.verticalLayout_2.addWidget(self.pushButton_tea_info)
        self.pushButton_course_info = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_course_info.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_course_info.setObjectName("pushButton_course_info")
        self.verticalLayout_2.addWidget(self.pushButton_course_info)
        self.pushButton_couchos_info = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_couchos_info.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_couchos_info.setObjectName("pushButton_couchos_info")
        self.verticalLayout_2.addWidget(self.pushButton_couchos_info)
        self.pushButton_stats_info = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_stats_info.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_stats_info.setObjectName("pushButton_stats_info")
        self.verticalLayout_2.addWidget(self.pushButton_stats_info)
        self.pushButton_web = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_web.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_web.setObjectName("pushButton_web")
        self.verticalLayout_2.addWidget(self.pushButton_web)
        self.pushButton_my = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_my.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_my.setObjectName("pushButton_my")
        self.verticalLayout_2.addWidget(self.pushButton_my)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.frame_89 = QtWidgets.QFrame(self.page_home)
        self.frame_89.setGeometry(QtCore.QRect(190, 160, 311, 161))
        self.frame_89.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_89.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_89.setObjectName("frame_89")
        self.verticalLayout_66 = QtWidgets.QVBoxLayout(self.frame_89)
        self.verticalLayout_66.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_66.setSpacing(0)
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.frame_91 = QtWidgets.QFrame(self.frame_89)
        self.frame_91.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_91.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_91.setObjectName("frame_91")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.frame_91)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label = QtWidgets.QLabel(self.frame_91)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 18pt \"幼圆\";")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_53.addWidget(self.label)
        self.verticalLayout_66.addWidget(self.frame_91)
        self.frame_90 = QtWidgets.QFrame(self.frame_89)
        self.frame_90.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_90.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_90.setObjectName("frame_90")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.frame_90)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_106 = QtWidgets.QLabel(self.frame_90)
        self.label_106.setMinimumSize(QtCore.QSize(0, 50))
        self.label_106.setStyleSheet("font: 16pt \"幼圆\";")
        self.label_106.setObjectName("label_106")
        self.horizontalLayout_52.addWidget(self.label_106)
        self.label_role = QtWidgets.QLabel(self.frame_90)
        self.label_role.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_role.setText("")
        self.label_role.setObjectName("label_role")
        self.horizontalLayout_52.addWidget(self.label_role)
        self.verticalLayout_66.addWidget(self.frame_90)
        self.label_4 = QtWidgets.QLabel(self.page_home)
        self.label_4.setGeometry(QtCore.QRect(580, 490, 131, 16))
        self.label_4.setStyleSheet("font:10pt \"幼圆\";")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_home)
        self.page_stu_info = QtWidgets.QWidget()
        self.page_stu_info.setObjectName("page_stu_info")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_stu_info)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_26 = QtWidgets.QFrame(self.page_stu_info)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.frame_26)
        self.label_8.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_21.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setStyleSheet("QPushButton{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"#frame_27{\n"
"border:1px solid;\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_9.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_15.addWidget(self.pushButton_9)
        self.lineEdit_stu = QtWidgets.QLineEdit(self.frame_27)
        self.lineEdit_stu.setStyleSheet("border: 1px solid;\n"
"border-radius:5px;\n"
"font: 9pt \"Adobe 黑体 Std R\";")
        self.lineEdit_stu.setObjectName("lineEdit_stu")
        self.horizontalLayout_15.addWidget(self.lineEdit_stu)
        self.label_19 = QtWidgets.QLabel(self.frame_27)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.pushButton_stu_q = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_stu_q.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_stu_q.setObjectName("pushButton_stu_q")
        self.horizontalLayout_15.addWidget(self.pushButton_stu_q)
        self.label_3 = QtWidgets.QLabel(self.frame_27)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_15.addWidget(self.label_3)
        self.pushButton_insert_stu = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_insert_stu.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_insert_stu.setObjectName("pushButton_insert_stu")
        self.horizontalLayout_15.addWidget(self.pushButton_insert_stu)
        self.label_20 = QtWidgets.QLabel(self.frame_27)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.pushButton_stu_qall = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_stu_qall.setMinimumSize(QtCore.QSize(100, 18))
        self.pushButton_stu_qall.setObjectName("pushButton_stu_qall")
        self.horizontalLayout_15.addWidget(self.pushButton_stu_qall)
        self.label_21 = QtWidgets.QLabel(self.frame_27)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.pushButton_stu_delete = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_stu_delete.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_stu_delete.setObjectName("pushButton_stu_delete")
        self.horizontalLayout_15.addWidget(self.pushButton_stu_delete)
        self.label_107 = QtWidgets.QLabel(self.frame_27)
        self.label_107.setText("")
        self.label_107.setObjectName("label_107")
        self.horizontalLayout_15.addWidget(self.label_107)
        self.pushButton_stu_clear = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_stu_clear.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_stu_clear.setObjectName("pushButton_stu_clear")
        self.horizontalLayout_15.addWidget(self.pushButton_stu_clear)
        self.verticalLayout_21.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tableView_stu = QtWidgets.QTableView(self.frame_28)
        self.tableView_stu.setStyleSheet("QTableView{\n"
"    border:none;\n"
"    border-left: 1px solid;\n"
"    border-top: 1px solid;\n"
"}\n"
"QTableView::item {\n"
"    border: none;\n"
"    border-right: none;\n"
"    border-bottom: none;\n"
"}\n"
"")
        self.tableView_stu.setObjectName("tableView_stu")
        self.tableView_stu.verticalHeader().setVisible(False)
        self.verticalLayout_22.addWidget(self.tableView_stu)
        self.frame_11 = QtWidgets.QFrame(self.frame_28)
        self.frame_11.setStyleSheet("#pushButton_modify{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"#pushButton_modify:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"#pushButton_modify:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-bottom:0.5px solid;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_stu_before = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_stu_before.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_stu_before.setReadOnly(True)
        self.lineEdit_stu_before.setObjectName("lineEdit_stu_before")
        self.horizontalLayout_16.addWidget(self.lineEdit_stu_before)
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_12.setStyleSheet("border:none")
        self.pushButton_12.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon5)
        self.pushButton_12.setIconSize(QtCore.QSize(90, 16))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.lineEdit_stu_after = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_stu_after.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_stu_after.setObjectName("lineEdit_stu_after")
        self.horizontalLayout_16.addWidget(self.lineEdit_stu_after)
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.pushButton_stu_modify = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_stu_modify.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_stu_modify.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_stu_modify.setObjectName("pushButton_stu_modify")
        self.horizontalLayout_16.addWidget(self.pushButton_stu_modify)
        self.verticalLayout_22.addWidget(self.frame_11)
        self.verticalLayout_21.addWidget(self.frame_28)
        self.verticalLayout_11.addWidget(self.frame_26)
        self.stackedWidget.addWidget(self.page_stu_info)
        self.page_web = QtWidgets.QWidget()
        self.page_web.setObjectName("page_web")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_web)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.page_web)
        self.frame_8.setMinimumSize(QtCore.QSize(370, 390))
        self.frame_8.setMaximumSize(QtCore.QSize(370, 390))
        self.frame_8.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_blbl = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_blbl.setMinimumSize(QtCore.QSize(0, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/bilibili.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_blbl.setIcon(icon6)
        self.pushButton_blbl.setIconSize(QtCore.QSize(20, 16))
        self.pushButton_blbl.setObjectName("pushButton_blbl")
        self.verticalLayout_3.addWidget(self.pushButton_blbl)
        self.pushButton_csdn = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_csdn.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_csdn.setIcon(icon)
        self.pushButton_csdn.setObjectName("pushButton_csdn")
        self.verticalLayout_3.addWidget(self.pushButton_csdn)
        self.pushButton_apple = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_apple.setMinimumSize(QtCore.QSize(0, 25))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/apple.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_apple.setIcon(icon7)
        self.pushButton_apple.setObjectName("pushButton_apple")
        self.verticalLayout_3.addWidget(self.pushButton_apple)
        self.pushButton_TV = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_TV.setMinimumSize(QtCore.QSize(0, 25))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/tencent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TV.setIcon(icon8)
        self.pushButton_TV.setObjectName("pushButton_TV")
        self.verticalLayout_3.addWidget(self.pushButton_TV)
        self.pushButton_scut = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_scut.setMinimumSize(QtCore.QSize(0, 25))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/scut.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_scut.setIcon(icon9)
        self.pushButton_scut.setIconSize(QtCore.QSize(70, 16))
        self.pushButton_scut.setObjectName("pushButton_scut")
        self.verticalLayout_3.addWidget(self.pushButton_scut)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_web)
        self.page_my = QtWidgets.QWidget()
        self.page_my.setObjectName("page_my")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_my)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.page_my)
        self.frame_9.setMinimumSize(QtCore.QSize(370, 390))
        self.frame_9.setMaximumSize(QtCore.QSize(370, 390))
        self.frame_9.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_M_pass1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_M_pass1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_M_pass1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_M_pass1.setObjectName("lineEdit_M_pass1")
        self.verticalLayout_4.addWidget(self.lineEdit_M_pass1)
        self.lineEdit_M_pass2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_M_pass2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_M_pass2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_M_pass2.setObjectName("lineEdit_M_pass2")
        self.verticalLayout_4.addWidget(self.lineEdit_M_pass2)
        self.pushButton_M_sure = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_M_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_M_sure.setObjectName("pushButton_M_sure")
        self.verticalLayout_4.addWidget(self.pushButton_M_sure)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_9)
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_my)
        self.page_tea_info = QtWidgets.QWidget()
        self.page_tea_info.setObjectName("page_tea_info")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_tea_info)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.page_tea_info)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.frame_17)
        self.label_5.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.frame_30 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_30.sizePolicy().hasHeightForWidth())
        self.frame_30.setSizePolicy(sizePolicy)
        self.frame_30.setStyleSheet("QPushButton{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"#frame_30{\n"
"border:1px solid;\n"
"}")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_18.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_13.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon4)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_18.addWidget(self.pushButton_13)
        self.lineEdit_tea = QtWidgets.QLineEdit(self.frame_30)
        self.lineEdit_tea.setStyleSheet("border: 1px solid;\n"
"border-radius:5px;\n"
"font: 9pt \"Adobe 黑体 Std R\";")
        self.lineEdit_tea.setObjectName("lineEdit_tea")
        self.horizontalLayout_18.addWidget(self.lineEdit_tea)
        self.label_22 = QtWidgets.QLabel(self.frame_30)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.pushButton_tea_q = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_tea_q.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_tea_q.setObjectName("pushButton_tea_q")
        self.horizontalLayout_18.addWidget(self.pushButton_tea_q)
        self.label_23 = QtWidgets.QLabel(self.frame_30)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.pushButton_insert_tea = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_insert_tea.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_insert_tea.setObjectName("pushButton_insert_tea")
        self.horizontalLayout_18.addWidget(self.pushButton_insert_tea)
        self.label_31 = QtWidgets.QLabel(self.frame_30)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_18.addWidget(self.label_31)
        self.pushButton_tea_qall = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_tea_qall.setMinimumSize(QtCore.QSize(100, 18))
        self.pushButton_tea_qall.setObjectName("pushButton_tea_qall")
        self.horizontalLayout_18.addWidget(self.pushButton_tea_qall)
        self.label_24 = QtWidgets.QLabel(self.frame_30)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        self.pushButton_tea_clear = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_tea_clear.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_tea_clear.setObjectName("pushButton_tea_clear")
        self.horizontalLayout_18.addWidget(self.pushButton_tea_clear)
        self.verticalLayout_12.addWidget(self.frame_30)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_30 = QtWidgets.QLabel(self.frame_19)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_13.addWidget(self.label_30)
        self.tableView_tea = QtWidgets.QTableView(self.frame_19)
        self.tableView_tea.setStyleSheet("QTableView{\n"
"    border:none;\n"
"    border-left: 1px solid;\n"
"    border-top: 1px solid;\n"
"}\n"
"QTableView::item {\n"
"    border: none;\n"
"    border-right: none;\n"
"    border-bottom: none;\n"
"}\n"
"")
        self.tableView_tea.setObjectName("tableView_tea")
        self.tableView_tea.verticalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.tableView_tea)
        self.frame_18 = QtWidgets.QFrame(self.frame_19)
        self.frame_18.setStyleSheet("#pushButton_modify{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"#pushButton_modify:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"#pushButton_modify:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-bottom:0.5px solid;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_tea_before = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_tea_before.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tea_before.setReadOnly(True)
        self.lineEdit_tea_before.setObjectName("lineEdit_tea_before")
        self.horizontalLayout_20.addWidget(self.lineEdit_tea_before)
        self.label_28 = QtWidgets.QLabel(self.frame_18)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_15.setStyleSheet("border:none")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon5)
        self.pushButton_15.setIconSize(QtCore.QSize(90, 16))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_20.addWidget(self.pushButton_15)
        self.lineEdit_tea_after = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_tea_after.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_tea_after.setObjectName("lineEdit_tea_after")
        self.horizontalLayout_20.addWidget(self.lineEdit_tea_after)
        self.label_29 = QtWidgets.QLabel(self.frame_18)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_20.addWidget(self.label_29)
        self.pushButton_tea_modify = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_tea_modify.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_tea_modify.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_tea_modify.setObjectName("pushButton_tea_modify")
        self.horizontalLayout_20.addWidget(self.pushButton_tea_modify)
        self.verticalLayout_13.addWidget(self.frame_18)
        self.verticalLayout_12.addWidget(self.frame_19)
        self.verticalLayout_14.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.page_tea_info)
        self.page_course_info = QtWidgets.QWidget()
        self.page_course_info.setObjectName("page_course_info")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_course_info)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_20 = QtWidgets.QFrame(self.page_course_info)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.frame_20)
        self.label_6.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.frame_29 = QtWidgets.QFrame(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setStyleSheet("QPushButton{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"#frame_29{\n"
"border:1px solid;\n"
"}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_17.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_10.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_17.addWidget(self.pushButton_10)
        self.lineEdit_course = QtWidgets.QLineEdit(self.frame_29)
        self.lineEdit_course.setStyleSheet("border: 1px solid;\n"
"border-radius:5px;\n"
"font: 9pt \"Adobe 黑体 Std R\";")
        self.lineEdit_course.setObjectName("lineEdit_course")
        self.horizontalLayout_17.addWidget(self.lineEdit_course)
        self.label_16 = QtWidgets.QLabel(self.frame_29)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.pushButton_course_q = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_course_q.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_course_q.setObjectName("pushButton_course_q")
        self.horizontalLayout_17.addWidget(self.pushButton_course_q)
        self.label_33 = QtWidgets.QLabel(self.frame_29)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        self.pushButton_insert_course = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_insert_course.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_insert_course.setObjectName("pushButton_insert_course")
        self.horizontalLayout_17.addWidget(self.pushButton_insert_course)
        self.label_17 = QtWidgets.QLabel(self.frame_29)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.pushButton_delete_course = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_delete_course.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_delete_course.setObjectName("pushButton_delete_course")
        self.horizontalLayout_17.addWidget(self.pushButton_delete_course)
        self.label_32 = QtWidgets.QLabel(self.frame_29)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_17.addWidget(self.label_32)
        self.pushButton_course_qall = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_course_qall.setMinimumSize(QtCore.QSize(100, 18))
        self.pushButton_course_qall.setObjectName("pushButton_course_qall")
        self.horizontalLayout_17.addWidget(self.pushButton_course_qall)
        self.label_18 = QtWidgets.QLabel(self.frame_29)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.pushButton_course_clear = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_course_clear.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_course_clear.setObjectName("pushButton_course_clear")
        self.horizontalLayout_17.addWidget(self.pushButton_course_clear)
        self.verticalLayout_15.addWidget(self.frame_29)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tableView_course = QtWidgets.QTableView(self.frame_22)
        self.tableView_course.setStyleSheet("QTableView{\n"
"    border:none;\n"
"    border-left: 1px solid;\n"
"    border-top: 1px solid;\n"
"}\n"
"QTableView::item {\n"
"    border: none;\n"
"    border-right: none;\n"
"    border-bottom: none;\n"
"}\n"
"")
        self.tableView_course.setObjectName("tableView_course")
        self.tableView_course.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tableView_course)
        self.label_27 = QtWidgets.QLabel(self.frame_22)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_16.addWidget(self.label_27)
        self.verticalLayout_15.addWidget(self.frame_22)
        self.verticalLayout_17.addWidget(self.frame_20)
        self.frame_16 = QtWidgets.QFrame(self.page_course_info)
        self.frame_16.setStyleSheet("#pushButton_modify{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"#pushButton_modify:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"#pushButton_modify:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-bottom:0.5px solid;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEdit_course_before = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_course_before.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_course_before.setReadOnly(True)
        self.lineEdit_course_before.setObjectName("lineEdit_course_before")
        self.horizontalLayout_19.addWidget(self.lineEdit_course_before)
        self.label_25 = QtWidgets.QLabel(self.frame_16)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_19.addWidget(self.label_25)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_14.setStyleSheet("border:none")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon5)
        self.pushButton_14.setIconSize(QtCore.QSize(90, 16))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_19.addWidget(self.pushButton_14)
        self.lineEdit_course_after = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_course_after.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_course_after.setObjectName("lineEdit_course_after")
        self.horizontalLayout_19.addWidget(self.lineEdit_course_after)
        self.label_26 = QtWidgets.QLabel(self.frame_16)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.pushButton_course_modify = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_course_modify.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_course_modify.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_course_modify.setObjectName("pushButton_course_modify")
        self.horizontalLayout_19.addWidget(self.pushButton_course_modify)
        self.verticalLayout_17.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.page_course_info)
        self.page_couchos = QtWidgets.QWidget()
        self.page_couchos.setObjectName("page_couchos")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_couchos)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_23 = QtWidgets.QFrame(self.page_couchos)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.frame_23)
        self.label_7.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setStyleSheet("QPushButton{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"#frame_24{\n"
"border:0.5px solid;\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_14.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_8.setStyleSheet("border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_14.addWidget(self.pushButton_8)
        self.lineEdit_couchos = QtWidgets.QLineEdit(self.frame_24)
        self.lineEdit_couchos.setStyleSheet("border: 1px solid;\n"
"border-radius:5px;\n"
"font: 9pt \"Adobe 黑体 Std R\";")
        self.lineEdit_couchos.setObjectName("lineEdit_couchos")
        self.horizontalLayout_14.addWidget(self.lineEdit_couchos)
        self.label_10 = QtWidgets.QLabel(self.frame_24)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.pushButton_couchos_q = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_couchos_q.setMinimumSize(QtCore.QSize(50, 18))
        self.pushButton_couchos_q.setObjectName("pushButton_couchos_q")
        self.horizontalLayout_14.addWidget(self.pushButton_couchos_q)
        self.label_2 = QtWidgets.QLabel(self.frame_24)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        self.pushButton_couchos_qall = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_couchos_qall.setMinimumSize(QtCore.QSize(100, 18))
        self.pushButton_couchos_qall.setObjectName("pushButton_couchos_qall")
        self.horizontalLayout_14.addWidget(self.pushButton_couchos_qall)
        self.label_9 = QtWidgets.QLabel(self.frame_24)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.pushButton_couchos_clear = QtWidgets.QPushButton(self.frame_24)
        self.pushButton_couchos_clear.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_couchos_clear.setObjectName("pushButton_couchos_clear")
        self.horizontalLayout_14.addWidget(self.pushButton_couchos_clear)
        self.verticalLayout_18.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tableView_couchos = QtWidgets.QTableView(self.frame_25)
        self.tableView_couchos.setStyleSheet("QTableView{\n"
"    border:none;\n"
"    border-left: 1px solid;\n"
"    border-top: 1px solid;\n"
"}\n"
"QTableView::item {\n"
"    border: none;\n"
"    border-right: none;\n"
"    border-bottom: none;\n"
"}\n"
"")
        self.tableView_couchos.setObjectName("tableView_couchos")
        self.tableView_couchos.verticalHeader().setVisible(False)
        self.verticalLayout_19.addWidget(self.tableView_couchos)
        self.label_13 = QtWidgets.QLabel(self.frame_25)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_19.addWidget(self.label_13)
        self.frame_10 = QtWidgets.QFrame(self.frame_25)
        self.frame_10.setStyleSheet("#pushButton_modify{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"#pushButton_modify:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"#pushButton_modify:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-bottom:0.5px solid;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_couchos_before = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_couchos_before.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_couchos_before.setReadOnly(True)
        self.lineEdit_couchos_before.setObjectName("lineEdit_couchos_before")
        self.horizontalLayout_8.addWidget(self.lineEdit_couchos_before)
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_11.setStyleSheet("border:none")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(90, 16))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_8.addWidget(self.pushButton_11)
        self.lineEdit_couchos_after = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_couchos_after.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_couchos_after.setObjectName("lineEdit_couchos_after")
        self.horizontalLayout_8.addWidget(self.lineEdit_couchos_after)
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.pushButton_couchos_modify = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_couchos_modify.setMinimumSize(QtCore.QSize(55, 18))
        self.pushButton_couchos_modify.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_couchos_modify.setObjectName("pushButton_couchos_modify")
        self.horizontalLayout_8.addWidget(self.pushButton_couchos_modify)
        self.verticalLayout_19.addWidget(self.frame_10)
        self.verticalLayout_18.addWidget(self.frame_25)
        self.verticalLayout_20.addWidget(self.frame_23)
        self.stackedWidget.addWidget(self.page_couchos)
        self.page_stats = QtWidgets.QWidget()
        self.page_stats.setObjectName("page_stats")
        self.verticalLayout_65 = QtWidgets.QVBoxLayout(self.page_stats)
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.frame_31 = QtWidgets.QFrame(self.page_stats)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_77 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_77.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_77.setSpacing(0)
        self.verticalLayout_77.setObjectName("verticalLayout_77")
        self.frame_86 = QtWidgets.QFrame(self.frame_31)
        self.frame_86.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_86.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_86.setObjectName("frame_86")
        self.verticalLayout_63 = QtWidgets.QVBoxLayout(self.frame_86)
        self.verticalLayout_63.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_63.setSpacing(0)
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.label_105 = QtWidgets.QLabel(self.frame_86)
        self.label_105.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_105.setObjectName("label_105")
        self.verticalLayout_63.addWidget(self.label_105, 0, QtCore.Qt.AlignHCenter)
        self.frame_87 = QtWidgets.QFrame(self.frame_86)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_87.sizePolicy().hasHeightForWidth())
        self.frame_87.setSizePolicy(sizePolicy)
        self.frame_87.setStyleSheet("QPushButton{\n"
"    background-color: rgb(195, 195, 195);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:2px;\n"
"    padding-top:2px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(166, 168, 255);\n"
"}\n"
"\n"
"#frame_87{\n"
"border:1px solid;\n"
"}")
        self.frame_87.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_87.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_87.setObjectName("frame_87")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.frame_87)
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.pushButton_stat_stu_avg = QtWidgets.QPushButton(self.frame_87)
        self.pushButton_stat_stu_avg.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButton_stat_stu_avg.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_stat_stu_avg.setObjectName("pushButton_stat_stu_avg")
        self.horizontalLayout_51.addWidget(self.pushButton_stat_stu_avg)
        self.pushButton_stat_course_avg = QtWidgets.QPushButton(self.frame_87)
        self.pushButton_stat_course_avg.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_stat_course_avg.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_stat_course_avg.setObjectName("pushButton_stat_course_avg")
        self.horizontalLayout_51.addWidget(self.pushButton_stat_course_avg)
        self.pushButton_stat_clear = QtWidgets.QPushButton(self.frame_87)
        self.pushButton_stat_clear.setMinimumSize(QtCore.QSize(55, 30))
        self.pushButton_stat_clear.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_stat_clear.setObjectName("pushButton_stat_clear")
        self.horizontalLayout_51.addWidget(self.pushButton_stat_clear)
        self.verticalLayout_63.addWidget(self.frame_87)
        self.frame_88 = QtWidgets.QFrame(self.frame_86)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_88.sizePolicy().hasHeightForWidth())
        self.frame_88.setSizePolicy(sizePolicy)
        self.frame_88.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_88.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_88.setObjectName("frame_88")
        self.verticalLayout_64 = QtWidgets.QVBoxLayout(self.frame_88)
        self.verticalLayout_64.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_64.setSpacing(0)
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.tableView_stats = QtWidgets.QTableView(self.frame_88)
        self.tableView_stats.setStyleSheet("QTableView{\n"
"    border:none;\n"
"    border-left: 1px solid;\n"
"    border-top: 1px solid;\n"
"}\n"
"QTableView::item {\n"
"    border: none;\n"
"    border-right: none;\n"
"    border-bottom: none;\n"
"}\n"
"")
        self.tableView_stats.setObjectName("tableView_stats")
        self.tableView_stats.verticalHeader().setVisible(False)
        self.verticalLayout_64.addWidget(self.tableView_stats)
        self.label_109 = QtWidgets.QLabel(self.frame_88)
        self.label_109.setText("")
        self.label_109.setObjectName("label_109")
        self.verticalLayout_64.addWidget(self.label_109)
        self.verticalLayout_63.addWidget(self.frame_88)
        self.verticalLayout_77.addWidget(self.frame_86)
        self.verticalLayout_65.addWidget(self.frame_31)
        self.stackedWidget.addWidget(self.page_stats)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Konchok"))
        self.pushButton.setText(_translate("MainWindow", "MIS"))
        self.pushButton_home.setText(_translate("MainWindow", "首页"))
        self.pushButton_stu_info.setText(_translate("MainWindow", "学生信息"))
        self.pushButton_tea_info.setText(_translate("MainWindow", "教师信息"))
        self.pushButton_course_info.setText(_translate("MainWindow", "课程信息"))
        self.pushButton_couchos_info.setText(_translate("MainWindow", "课程选择信息"))
        self.pushButton_stats_info.setText(_translate("MainWindow", "成绩统计"))
        self.pushButton_web.setText(_translate("MainWindow", "网址推荐"))
        self.pushButton_my.setText(_translate("MainWindow", "我的"))
        self.label.setText(_translate("MainWindow", "Welcome to MIS!"))
        self.label_106.setText(_translate("MainWindow", "Your role:"))
        self.label_4.setText(_translate("MainWindow", "Author:YJS"))
        self.label_8.setText(_translate("MainWindow", "学生信息查询表"))
        self.lineEdit_stu.setPlaceholderText(_translate("MainWindow", "请输入学号或姓名"))
        self.pushButton_stu_q.setText(_translate("MainWindow", "查询"))
        self.pushButton_insert_stu.setText(_translate("MainWindow", "添加"))
        self.pushButton_stu_qall.setText(_translate("MainWindow", "查询全部信息"))
        self.pushButton_stu_delete.setText(_translate("MainWindow", "删除行"))
        self.pushButton_stu_clear.setText(_translate("MainWindow", "清除"))
        self.lineEdit_stu_before.setPlaceholderText(_translate("MainWindow", "修改前"))
        self.lineEdit_stu_after.setPlaceholderText(_translate("MainWindow", "修改后"))
        self.pushButton_stu_modify.setText(_translate("MainWindow", "修改"))
        self.pushButton_blbl.setText(_translate("MainWindow", "BILIBILI"))
        self.pushButton_csdn.setText(_translate("MainWindow", "CSDN"))
        self.pushButton_apple.setText(_translate("MainWindow", "APPLE"))
        self.pushButton_TV.setText(_translate("MainWindow", "TENCENT VIDEO"))
        self.pushButton_scut.setText(_translate("MainWindow", "SCUT"))
        self.lineEdit_M_pass1.setInputMask(_translate("MainWindow", "密码："))
        self.lineEdit_M_pass1.setText(_translate("MainWindow", "密码："))
        self.lineEdit_M_pass2.setInputMask(_translate("MainWindow", "确认密码："))
        self.pushButton_M_sure.setText(_translate("MainWindow", "确定"))
        self.label_5.setText(_translate("MainWindow", "教师信息查询表"))
        self.lineEdit_tea.setPlaceholderText(_translate("MainWindow", "请输入教工号或姓名"))
        self.pushButton_tea_q.setText(_translate("MainWindow", "查询"))
        self.pushButton_insert_tea.setText(_translate("MainWindow", "添加"))
        self.pushButton_tea_qall.setText(_translate("MainWindow", "查询全部信息"))
        self.pushButton_tea_clear.setText(_translate("MainWindow", "清除"))
        self.lineEdit_tea_before.setPlaceholderText(_translate("MainWindow", "修改前"))
        self.lineEdit_tea_after.setPlaceholderText(_translate("MainWindow", "修改后"))
        self.pushButton_tea_modify.setText(_translate("MainWindow", "修改"))
        self.label_6.setText(_translate("MainWindow", "课程信息查询表"))
        self.lineEdit_course.setPlaceholderText(_translate("MainWindow", "请输入课程名或课程ID"))
        self.pushButton_course_q.setText(_translate("MainWindow", "查询"))
        self.pushButton_insert_course.setText(_translate("MainWindow", "添加"))
        self.pushButton_delete_course.setText(_translate("MainWindow", "删除行"))
        self.pushButton_course_qall.setText(_translate("MainWindow", "查询全部信息"))
        self.pushButton_course_clear.setText(_translate("MainWindow", "清除"))
        self.lineEdit_course_before.setPlaceholderText(_translate("MainWindow", "修改前"))
        self.lineEdit_course_after.setPlaceholderText(_translate("MainWindow", "修改后"))
        self.pushButton_course_modify.setText(_translate("MainWindow", "修改"))
        self.label_7.setText(_translate("MainWindow", "课程选择信息查询表"))
        self.lineEdit_couchos.setPlaceholderText(_translate("MainWindow", "请输入课程名"))
        self.pushButton_couchos_q.setText(_translate("MainWindow", "查询"))
        self.pushButton_couchos_qall.setText(_translate("MainWindow", "查询全部信息"))
        self.pushButton_couchos_clear.setText(_translate("MainWindow", "清除"))
        self.lineEdit_couchos_before.setPlaceholderText(_translate("MainWindow", "修改前"))
        self.lineEdit_couchos_after.setPlaceholderText(_translate("MainWindow", "修改后"))
        self.pushButton_couchos_modify.setText(_translate("MainWindow", "修改"))
        self.label_105.setText(_translate("MainWindow", "成绩统计"))
        self.pushButton_stat_stu_avg.setText(_translate("MainWindow", "学生个人均分"))
        self.pushButton_stat_course_avg.setText(_translate("MainWindow", "课程学生均分"))
        self.pushButton_stat_clear.setText(_translate("MainWindow", "清除"))
import res_rc
