# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 602)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 80, 281, 401))
        self.frame.setStyleSheet("#frame\n"
"{background-color: qlineargradient(spread:pad, x1:0.52835, y1:0, x2:0.534, y2:0.948864, stop:0 rgba(45, 77, 218, 220), stop:1 rgba(227, 0, 0, 224));\n"
"\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 120, 231, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Algerian\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 151, 101))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 12pt \"Adobe 宋体 Std L\";")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(360, 100, 271, 371))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(240, 10, 21, 20))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(26, 26))
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 30, 281, 341))
        self.frame_3.setMinimumSize(QtCore.QSize(281, 341))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(279, 297))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_register)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_R_account = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_account.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_account.setStyleSheet("")
        self.lineEdit_R_account.setObjectName("lineEdit_R_account")
        self.verticalLayout_6.addWidget(self.lineEdit_R_account)
        self.lineEdit_R_password1 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_password1.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_R_password1.setObjectName("lineEdit_R_password1")
        self.verticalLayout_6.addWidget(self.lineEdit_R_password1)
        self.lineEdit_R_password2 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_password2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_R_password2.setObjectName("lineEdit_R_password2")
        self.verticalLayout_6.addWidget(self.lineEdit_R_password2)
        self.lineEdit_R_role = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_role.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_role.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_R_role.setObjectName("lineEdit_R_role")
        self.verticalLayout_6.addWidget(self.lineEdit_R_role)
        self.pushButton_R_sure = QtWidgets.QPushButton(self.page_register)
        self.pushButton_R_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_R_sure.setObjectName("pushButton_R_sure")
        self.verticalLayout_6.addWidget(self.pushButton_R_sure)
        self.stackedWidget_2.addWidget(self.page_register)
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_L_account = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_account.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_account.setObjectName("lineEdit_L_account")
        self.verticalLayout_5.addWidget(self.lineEdit_L_account)
        self.lineEdit_L_password = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_password.setObjectName("lineEdit_L_password")
        self.verticalLayout_5.addWidget(self.lineEdit_L_password)
        self.pushButton_L_sure = QtWidgets.QPushButton(self.page_Login)
        self.pushButton_L_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_sure.setObjectName("pushButton_L_sure")
        self.verticalLayout_5.addWidget(self.pushButton_L_sure)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_register = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_register.setGeometry(QtCore.QRect(30, 10, 75, 23))
        self.pushButton_register.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_register.setIcon(icon1)
        self.pushButton_register.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_login = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_login.setGeometry(QtCore.QRect(160, 10, 75, 23))
        self.pushButton_login.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login.setIcon(icon2)
        self.pushButton_login.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setStyleSheet("color: rgb(255, 85, 127);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setMaximumSize(QtCore.QSize(132, 16777215))
        self.label_4.setStyleSheet("color: rgb(255, 85, 127);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2.raise_()
        self.frame.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Welcome database!"))
        self.label_2.setText(_translate("LoginWindow", "Thanks for viewing！"))
        self.lineEdit_R_account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_R_password1.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.lineEdit_R_password2.setPlaceholderText(_translate("LoginWindow", "确认密码："))
        self.lineEdit_R_role.setPlaceholderText(_translate("LoginWindow", "身份（student,teacher）"))
        self.pushButton_R_sure.setText(_translate("LoginWindow", "注册"))
        self.lineEdit_L_account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_L_password.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.pushButton_L_sure.setText(_translate("LoginWindow", "确认"))
        self.label_3.setText(_translate("LoginWindow", "账号或密码不能为空！"))
        self.label_4.setText(_translate("LoginWindow", "密码错误或账号不存在！"))
import res_rc
